seed: 42
exp_dir: /cognitive_comp/wutong/similarity_generation/experiments/
txl_config_path: /cognitive_comp/wutong/similarity_generation/model_utils/txl_1.1B_config.json
sim_data_path: /cognitive_comp/wutong/source/exp_data/sim_cycle_data/

txl_model_path: /cognitive_comp/wutong/source/model_base/model_zh/txl_zh_1.1B.pt
sp_model_path: /cognitive_comp/wutong/source/model_base/chinese_sentencepiece/cog-pretrain.model
dis_model_path: /cognitive_comp/wutong/source/model_base/pretrained_zh/macbert_large_mc
ckpt_model_path: /cognitive_comp/wutong/similarity_generation/experiments/lightning_logs/checkpoints/

data_path: /cognitive_comp/wutong/source/sim_data/raw_data/bustm
dis_ckpt_path: /cognitive_comp/wutong/finetune_large.bin

top_k: 0
top_p: 0.95
repetition_penalty: 1.0

dis_batch_size: 64
gen_batch_size: 6
gen_big_batch_size: 100
pre_gen_bs: 1024
pre_dis_bs: 512

max_thre0: 0.95
min_thre0: 0.7
max_thre1: 0.95
min_thre1: 0.9
max_dis_thre: 0.95
min_dis_thre: 0.85
add_thre: 0.01

dis_hidden_size: 1024
learning_rate: 1e-6
cycle_num: 5
cycle: -1
start: 0
end: 0
sentence_num: 3000

gen_train_steps: 50
dis_train_steps: 100
warmup_steps: 10
es_patience: 1
