seed: 42
exp_dir: /cognitive_comp/wutong/similarity_generation/experiments/

txl_config_path: /cognitive_comp/wutong/similarity_generation/model_utils/txl_5B_config.json

txl_model_path: /cognitive_comp/wutong/source/model_base/txl_zh_5.0B.pt
dis_model_path: /cognitive_comp/wutong/source/model_base/discriminator.pt
sp_model_path: /cognitive_comp/wutong/source/model_base/chinese_sentencepiece/cog-pretrain.model
ckpt_model_path: /cognitive_comp/wutong/similarity_generation/experiments/lightning_logs/checkpoints

wudao_data_path: /cognitive_comp/wutong/source/data_base/wudao_sentences
#  839196(Short(<10)), 1176(Long(>100)), 79696(△LCS<=1) 53388(△LCS<=2)
lab_data_path: /cognitive_comp/wutong/source/data_base/similarity_data/sim_cache_data
gen_data_path: /cognitive_comp/wutong/source/data_base/sim_cycle_data/gen_sim_data
score_data_path: /cognitive_comp/wutong/source/data_base/sim_cycle_data/score_sim_data
cache_data_path: /cognitive_comp/wutong/source/data_base/sim_cycle_cache

top_k: 0
top_p: 0.95

gen_threshold: 1.0
dis_threshold: 0.9  # Discriminator选择为0/1的阈值
gen_anti_cyle: -10  #  刚开始先对抗的轮数
gen_repeat_times: 2  # 每条句子重复生成的次数

dis_batch_size: 128  # 32 / 128
gen_batch_size: 2
gen_big_batch_size: 30
pre_gen_bs: 512
pre_dis_bs: 1024

pretrain_dis: False
dis_hidden_size: 1024
discriminator: 'IDEA-CCNL/Erlangshen-Roberta-330M-Similarity'

learning_rate: 2e-5
cycle_num: 15
cycle: -1

gen_train_steps: 200
dis_train_steps: 200
warmup_steps: 20
checkpoint_steps: 10
es_patience: 1
