seed: 42
exp_dir: /cognitive_comp/wutong/similarity_generation/experiments/

txl_config_path: /cognitive_comp/wutong/similarity_generation/model_utils/txl_5B_config.json

txl_model_path: /cognitive_comp/wutong/source/model_base/txl_zh_5.0B.pt
dis_model_path: /cognitive_comp/wutong/source/model_base/discriminator.pt
sp_model_path: /cognitive_comp/wutong/source/model_base/chinese_sentencepiece/cog-pretrain.model
ckpt_model_path: /cognitive_comp/wutong/similarity_generation/experiments/lightning_logs/checkpoints

wudao_data_path: /cognitive_comp/wutong/source/data_base/wudao_sentences
#  _new中将一堆相似句完全相同的score设置为0 (59285条 -> 371424(Equal)+97192->495201(Bad)
# 去掉了idea标注的数据，并且多了LCS<=2限制和最短长度10
lab_data_path: /cognitive_comp/wutong/source/data_base/similarity_data/sim_cache_data_new
gen_data_path: /cognitive_comp/wutong/source/data_base/sim_cycle_data/gen_sim_data
score_data_path: /cognitive_comp/wutong/source/data_base/sim_cycle_data/score_sim_data
cache_data_path: /cognitive_comp/wutong/source/data_base/sim_cycle_cache

dis_threshold: 0.7  # Discriminator选择为0/1的阈值
gen_anti_cyle: 3  #  刚开始先对抗的轮数
gen_repeat_times: 4  # 每条句子重复生成的次数
sentence_num: 1024  # 每一轮需要生成的句子数

dis_batch_size: 32
gen_batch_size: 2
gen_big_batch_size: 30
learning_rate: 2e-5

dis_hidden_size: 1024
discriminator: 'IDEA-CCNL/Erlangshen-Roberta-330M-Similarity'

epochs: 50
gen_train_steps: 2000
dis_train_steps: 2000
warmup_steps: 50
checkpoint_steps: 10
cycle_nums: 50
cycle: 0
